[package]
name = "belter-watchdog"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "belter-watchdog"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
toml.workspace = true
infractl-core = { path = "../infractl-core" }

[target.'cfg(unix)'.dependencies]
libc.workspace = true
signal-hook.workspace = true
